import type { Metadata, Viewport } from 'next';
import { Oleo_Script, Roboto } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { SessionProvider } from 'next-auth/react';
import { GlobalDialog } from '@/components/ReusableDialog';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import MobileSideBar from '@/components/MobileSidebar';
import { Toaster } from 'sonner';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

const oleo = Oleo_Script({
  variable: '--font-oleo-script',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'ValidateLens',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  keywords: ['nextjs', 'next14', 'pwa', 'next-pwa'],

  viewport:
    'minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover',
  icons: [
    { rel: 'apple-touch-icon', url: 'icon-192x192.png' },
    { rel: 'icon', url: 'icon-192x192.png' },
  ],
};

export const viewport: Viewport = {
  themeColor: [{ media: '(prefers-color-scheme: dark)', color: '#fff' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='manifest' href='/manifest.json' />
        <link rel='icon' href='/icons/icon-192x192.png' />
        <meta name='theme-color' content='#ffffff' />
      </head>
      <body className={`${roboto.className} ${oleo.variable} antialiased`}>
        <SidebarProvider>
          <SessionProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              disableTransitionOnChange>
              <div className='max-w-[1500px] mx-auto overflow-hidden p-2 w-full'>
                <div className='block md:hidden'>
                  <MobileSideBar />
                  <SidebarTrigger />
                </div>
                <div className='hidden md:block'>
                  <Navbar />
                </div>

                {children}
                <Toaster />
                <Footer />
                <GlobalDialog />
              </div>
            </ThemeProvider>
          </SessionProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
